name: North Law
favicon: null
layout_spectrum: 0.2825462503824383
typography_spectrum: 0.84467
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.02543473057448864
  lightness: 0.36483935778960586
  saturation: 0.02976460731588304
  rhythmicContrast: 0.5765090605709702
purpose: []
